import type { ConvertStep, Step } from './plan.ts';
import { Rejection } from './rejection.ts';
import { settings } from './settings.ts';

type Run = (value: unknown) => unknown;

/**
 * Any step a type's function runs.
 *
 * @internal
 */
export type AnyStep = Step | ConvertStep;

const isRun = (value: unknown): value is Run => typeof value === 'function';

const isCheck = (step: AnyStep): step is Step => 'accepts' in step;

/**
 * Text trimmed while the setting asks for it.
 *
 * @internal
 */
export const trimmedText = (text: string): string => (settings.trimStrings ? text.trim() : text);

/**
 * A string trimmed while the setting asks for it, anything else as it is.
 *
 * @internal
 */
export const trimmed = (value: unknown): unknown =>
  typeof value === 'string' ? trimmedText(value) : value;

/**
 * The step in front of the checks of a string type, which trims a string when
 * `n.configure({ normalize: { trimStrings: true } })` is set; the setting is read on each run.
 * A loop runs it as any other conversion, and generated code inlines it.
 *
 * @internal
 */
export const trimStep: ConvertStep = { convert: trimmed };

let probed: boolean | undefined;

// Code generation is how each type gets checks V8 can inline. Environments that forbid it, such as
// Cloudflare Workers or a strict Content-Security-Policy, throw here and fall back to a loop. The
// probe runs once, at the first function generated, so `codegen: 'off'` set at startup avoids it.
const probe = (): boolean => {
  try {
    // oxlint-disable-next-line typescript/no-implied-eval
    const built: unknown = new Function('return true');

    return isRun(built);
  } catch {
    return false;
  }
};

/**
 * Whether functions are generated now: not with `codegen: 'off'`, nor where the runtime
 * forbids it.
 *
 * @internal
 */
export const canGenerate = (): boolean => settings.codegen !== 'off' && (probed ??= probe());

/**
 * A function built from source with `new Function`, called with `values` for `names`,
 * or `undefined` where code generation is off or forbidden.
 *
 * @remarks
 * A generated function gets a call site of its own for everything it calls, which V8 can inline
 * where a function shared by every type can't. `generate` overrides the setting, for tests.
 *
 * @internal
 */
export const generateFunction = (
  names: readonly string[],
  source: string,
  values: readonly unknown[],
  generate: boolean = canGenerate(),
): ((...values: unknown[]) => unknown) | undefined => {
  if (!generate) {
    return undefined;
  }

  // @throws-ignore the source is generated by this package from valid JavaScript parts
  // oxlint-disable-next-line typescript/no-implied-eval
  const build: unknown = new Function(...names, `return ${source};`);
  const built: unknown =
    typeof build === 'function' ? Reflect.apply(build, undefined, values) : undefined;

  return isRun(built) ? built : undefined;
};

/**
 * A copy of `make` compiled again from its own source, so the functions it makes for one schema
 * get call sites of their own; `make` itself where code generation is off or forbidden.
 *
 * @remarks
 * One source serves both ways, where `generateFunction()` takes a source of its own. `make` must
 * read nothing but its parameters and globals such as `Object`, since the copy is compiled outside
 * the module.
 *
 * @internal
 */
export const freshCopy = <Make extends (...values: never[]) => unknown>(
  make: Make,
  generate: boolean = canGenerate(),
): Make => {
  if (!generate) {
    return make;
  }

  // @throws-ignore the source is the source of a function this package compiled already
  // oxlint-disable-next-line typescript/no-implied-eval
  const build: unknown = new Function(`return ${make.toString()};`);
  const built: unknown = typeof build === 'function' ? Reflect.apply(build, undefined, []) : make;

  // The copy is compiled from the source of `make`, so it is a function of the same type.
  // oxlint-disable-next-line typescript/no-unsafe-type-assertion
  return (typeof built === 'function' ? built : make) as Make;
};

const loopOver =
  (steps: readonly AnyStep[]): Run =>
  (input) => {
    let value = input;

    for (const step of steps) {
      if (isCheck(step)) {
        if (!step.accepts(value)) {
          return new Rejection(step.issues(value, input));
        }
      } else {
        value = step.convert(value);

        if (value instanceof Rejection) {
          return value;
        }
      }
    }

    return value;
  };

/**
 * The source of a trim step in a generated function, which reads `settings`.
 *
 * @internal
 */
export const trimSource =
  "if (settings.trimStrings && typeof value === 'string') value = value.trim();";

const generated = (steps: readonly AnyStep[], generate: boolean | undefined): Run => {
  const names: string[] = ['Rejection', 'settings'];
  const values: unknown[] = [Rejection, settings];
  const lines = steps.map((step, index) => {
    if (step === trimStep) {
      return trimSource;
    }

    if (isCheck(step)) {
      names.push(`accepts${index}`, `issues${index}`);
      values.push(step.accepts, step.issues);

      return `if (!accepts${index}(value)) return new Rejection(issues${index}(value, input));`;
    }

    names.push(`convert${index}`);
    values.push(step.convert);

    return `value = convert${index}(value); if (value instanceof Rejection) return value;`;
  });
  const compiled = generateFunction(
    names,
    `(input) => { let value = input; ${lines.join(' ')} return value; }`,
    values,
    generate,
  );

  return compiled ?? loopOver(steps);
};

/**
 * One function that runs every step of a type and returns the value, or the
 * `Rejection` of the first step that fails; generated per type, so the engine sees a call site of
 * its own for each check and can inline it.
 *
 * @remarks
 * A shared loop over the steps of every type makes its call site megamorphic, which V8 can't
 * inline; a function generated for one type keeps each call monomorphic. Rules from other
 * libraries are steps too, so a type mixing them with patterns is generated as well. Where code
 * generation is forbidden, the steps run through a loop instead.
 *
 * @internal
 */
export const compileRun = (steps: readonly AnyStep[], generate?: boolean): Run =>
  generate !== false && steps.length > 0 ? generated(steps, generate) : loopOver(steps);

/**
 * Whether a value carries the brand `key`, as one function per type, generated where
 * code generation is allowed.
 *
 * @remarks
 * A function shared by every type would read every brand at one property access, which the engine
 * can't optimise; a function per type reads one brand only.
 *
 * @internal
 */
export const brandCheck = (key: symbol, generate?: boolean): ((value: unknown) => boolean) => {
  const generatedCheck = generateFunction(
    ['key'],
    "(value) => typeof value === 'object' && value !== null && value[key] === true",
    [key],
    generate,
  );

  if (generatedCheck === undefined) {
    return (value) =>
      typeof value === 'object' && value !== null && Reflect.get(value, key) === true;
  }

  // The generated source is exactly this check; wrapping it again would share one call site
  // between all types and undo the point of generating it.
  // oxlint-disable-next-line typescript/no-unsafe-type-assertion
  return generatedCheck as (value: unknown) => boolean;
};
