import { describe, expect, it } from 'vitest';

import { columnKindOf } from '../../../src/adapters/orm/column.ts';
import {
  AnyBigInt,
  AnyBoolean,
  AnyNumber,
  AnyString,
  Base64,
  Base64Url,
  CountryCode,
  CurrencyCode,
  DomainName,
  Email,
  FiniteNumber,
  Float32,
  Gtin,
  HexColor,
  Hostname,
  HttpUrl,
  Int16,
  Int32,
  Int64,
  Int8,
  Integer,
  IpAddress,
  IpPrefix,
  Ipv4Address,
  Ipv4Prefix,
  Ipv6Address,
  Ipv6Prefix,
  Isbn,
  Isin,
  Issn,
  LanguageTag,
  Latitude,
  Longitude,
  MacAddress,
  MediaType,
  n,
  NegativeBigInt,
  NegativeInteger,
  NegativeNumber,
  Nominal,
  NonBlankString,
  NonEmptyString,
  NonNegativeBigInt,
  NonNegativeInteger,
  NonNegativeNumber,
  NonPositiveBigInt,
  NonPositiveInteger,
  NonPositiveNumber,
  ObjectId,
  Port,
  PositiveBigInt,
  PositiveInteger,
  PositiveNumber,
  SemVer,
  Uint16,
  Uint32,
  Uint64,
  Uint8,
  Ulid,
  Url,
  Uuid,
  UuidV4,
  UuidV7,
} from '../../../src/index.ts';

const Percent = Nominal(
  'columns.Percent',
  n.satisfying(
    (value: unknown): value is number =>
      typeof value === 'number' && Number.isInteger(value) && value >= 0 && value <= 100,
    'a percent',
  ),
);
const Flag = Nominal(
  'columns.Flag',
  n.satisfying((value: unknown): value is boolean => typeof value === 'boolean', 'a flag'),
);
const Code = Nominal('columns.Code', /^[A-Z]{3}$/u);
// Takes fractions, but none below 1.
const Price = Nominal(
  'columns.Price',
  n.satisfying(
    (value: unknown): value is number => typeof value === 'number' && value >= 1,
    'a price',
  ),
);

describe('columnKindOf', () => {
  it.each([
    [Email, { kind: 'text', length: 254 }],
    [Uuid, { kind: 'uuid' }],
    [UuidV4, { kind: 'uuid' }],
    [UuidV7, { kind: 'uuid' }],
    [Url, { kind: 'text' }],
    [HttpUrl, { kind: 'text' }],
    [CountryCode, { kind: 'text', length: 2 }],
    [CurrencyCode, { kind: 'text', length: 3 }],
    [LanguageTag, { kind: 'text' }],
    [AnyString, { kind: 'text' }],
    [MediaType, { kind: 'text' }],
    [HexColor, { kind: 'text', length: 9 }],
    [Base64, { kind: 'text' }],
    [Base64Url, { kind: 'text' }],
    [NonEmptyString, { kind: 'text' }],
    [NonBlankString, { kind: 'text' }],
    [Ulid, { kind: 'text', length: 26 }],
    [ObjectId, { kind: 'text', length: 24 }],
    [SemVer, { kind: 'text', length: 256 }],
    [Port, { kind: 'integer' }],
    [Latitude, { kind: 'double' }],
    [Longitude, { kind: 'double' }],
    [Hostname, { kind: 'text', length: 253 }],
    [DomainName, { kind: 'text', length: 253 }],
    [IpAddress, { kind: 'text', length: 45 }],
    [Ipv4Address, { kind: 'text', length: 15 }],
    [Ipv6Address, { kind: 'text', length: 45 }],
    [IpPrefix, { kind: 'text', length: 49 }],
    [Ipv4Prefix, { kind: 'text', length: 18 }],
    [Ipv6Prefix, { kind: 'text', length: 49 }],
    [MacAddress, { kind: 'text', length: 17 }],
    [Isbn, { kind: 'text', length: 13 }],
    [Issn, { kind: 'text', length: 9 }],
    [Gtin, { kind: 'text', length: 14 }],
    [Isin, { kind: 'text', length: 12 }],
    [Int8, { kind: 'integer' }],
    [Int16, { kind: 'integer' }],
    [Int32, { kind: 'integer' }],
    [Uint32, { kind: 'bigint' }],
    [Integer, { kind: 'bigint' }],
    [PositiveInteger, { kind: 'bigint' }],
    [NegativeInteger, { kind: 'bigint' }],
    [NonNegativeInteger, { kind: 'bigint' }],
    [NonPositiveInteger, { kind: 'bigint' }],
    [Uint8, { kind: 'integer' }],
    [Uint16, { kind: 'integer' }],
    [AnyNumber, { kind: 'double' }],
    [FiniteNumber, { kind: 'double' }],
    [PositiveNumber, { kind: 'double' }],
    [NegativeNumber, { kind: 'double' }],
    [NonNegativeNumber, { kind: 'double' }],
    [NonPositiveNumber, { kind: 'double' }],
    [Float32, { kind: 'double' }],
    [AnyBoolean, { kind: 'boolean' }],
    [Int64, { kind: 'bigint' }],
    [Uint64, { kind: 'decimal', precision: 20 }],
    [AnyBigInt, { kind: 'text', length: 1000 }],
    [PositiveBigInt, { kind: 'text', length: 1000 }],
    [NegativeBigInt, { kind: 'text', length: 1000 }],
    [NonNegativeBigInt, { kind: 'text', length: 1000 }],
    [NonPositiveBigInt, { kind: 'text', length: 1000 }],
  ])('stores %o in %o', (target, kind) => {
    expect(columnKindOf(target)).toStrictEqual(kind);
  });

  it('reads a type declared from scratch by what it accepts', () => {
    expect(columnKindOf(Percent)).toStrictEqual({ kind: 'integer' });
    expect(columnKindOf(Flag)).toStrictEqual({ kind: 'boolean' });
    expect(columnKindOf(Code)).toStrictEqual({ kind: 'text' });
    expect(columnKindOf(Price)).toStrictEqual({ kind: 'double' });
  });
});
