name: 'coverage'
on:
  pull_request:
    branches:
      - main
jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ github.token }}
