name: 'coverage'
on:
  pull_request:
    branches:
      - main
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - with:
          github-token: ${{ secrets.SECRET_TOKEN }}
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
